sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 0.10
  - 0.12
  - 4.4
  - 5.8
matrix:
    allow_failures:
        - node_js: 4.4
        - node_js: 5.8
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=units
script: "npm run $TEST_SUITE"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release